server:
  port: 8282
spring:
  datasource:
    url: jdbc:h2:mem:CourseEnrollment;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=create schema if not exists dbo\\;SET SCHEMA dbo\\;runscript from 'classpath:create.h2.sql';
    username: sa
    password:
    platform: h2
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false

