server:
  port: 8282
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/CourseEnrollment?serverTimezone=UTC
    username: enrollmentAppUser
    password: tempPwd123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: false